### ISSUE TITLE
Package install doesn't work (on multiple machines)

### ISSUE THREAD

**Issue by RussellGrayxd** [RangeShifter/RangeShiftR-package#2]
I have windows, updated R and updated Rtools

This is what happens upon install attempts

√  checking for file 'C:\Users\Russe\AppData\Local\Temp\Rtmpk7GY9b\remotes6d346432677b\RangeShifter-RangeShiftR-package-ed0a3ad/DESCRIPTION' ...
-  preparing 'RangeShiftR': (478ms)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  installing the package to process help pages
         -----------------------------------
-  installing *source* package 'RangeShiftR' ...
   ** using staged installation
   ** libs
   c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG  -I"C:/Users/Russe/Documents/R/win-library/3.6/Rcpp/include"     -DRSWIN64 -w   -O2 -Wall  -mtune=core2 -c Cell.cpp -o Cell.o
   c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG  -I"C:/Users/Russe/Documents/R/win-library/3.6/Rcpp/include"     -DRSWIN64 -w   -O2 -Wall  -mtune=core2 -c Community.cpp -o Community.o
   In file included from SubCommunity.h:55:0,
                    from Community.h:57,
                    from Community.cpp:25:
   Landscape.h:91:19: fatal error: codecvt: No such file or directory
    #include <codecvt>
                      ^
   compilation terminated.
   make: *** [C:/PROGRA~1/R/R-36~1.3/etc/x64/Makeconf:215: Community.o] Error 1
   ERROR: compilation failed for package 'RangeShiftR'
-  removing 'C:/Users/Russe/AppData/Local/Temp/Rtmpg1UpZR/Rinst176c153f495c/RangeShiftR'
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'RangeShiftR' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E>                  from Community.cpp:25:
E> Landscape.h:91:19: fatal error: codecvt: No such file or directory
E>  #include <codecvt>
E>                    ^
E> compilation terminated.
E> make: *** [C:/PROGRA~1/R/R-36~1.3/etc/x64/Makeconf:215: Community.o] Error 1
E> ERROR: compilation failed for package 'RangeShiftR'
E> * removing 'C:/Users/Russe/AppData/Local/Temp/Rtmpg1UpZR/Rinst176c153f495c/RangeShiftR'
E>       -----------------------------------
E> ERROR: package installation failed

**Comment by annekathleenmalchow** [comment]
Hi,
thanks for letting us know. Are all machines you have tried this on using Windows?
I am going to make some changes, hopefully it should work afterwards.
Best,
Anne

**Comment by annekathleenmalchow** [comment]
Hi again,
I have made a new commit that should hopefully fix the issue. 
The library 'codecvt' now is not needed for Windows anymore.
If you have time, please try again and let us know if it works.
Thanks,
Anne

**Comment by RussellGrayxd** [comment]
Yes all of them are windows. I believe the package compiling process is having some issue with Rtools for some reason, maybe a single line of compilation code that's missing a bracket, letter, or -/+ somewhere. Hopefully and easy fix!
--Russell J. Gray
Wildlife Ecology & Conservation Consultant
| 
0934581341 | rgrayherpetology@gmail.com
 |
| 
https://www.rjgrayecology.com/
 |
| 705 alligator ranch rd. New Smyrna Beach, FL, USA. 32168 |

 

    On Tuesday, December 1, 2020, 10:06:33 p.m. GMT+7, annekathleenmalchow <notifications@github.com> wrote:  
 
 


Hi again,
I have made a new commit that should hopefully fix the issue.
The library 'codecvt' now is not needed for Windows anymore.
If you have time, please try again and let us know if it works.
Thanks,
Anne

**Comment by annekathleenmalchow** [comment]
So have you tried the updated version already and does it still give the same error?

**Comment by RussellGrayxd** [comment]
I have tried:devtools::install_github("RangeShifter/RangeShiftR-package", ref="main")devtools::install_github("https://github.com/RangeShifter/RangeShiftR-package", ref = "main")

I have the newest version of Rtools, I have made sure the PATH is set, and have no issues using devtools to install any other packages. 


--Russell J. Gray
Wildlife Ecology & Conservation Consultant
| 
0934581341 | rgrayherpetology@gmail.com
 |
| 
https://www.rjgrayecology.com/
 |
| 705 alligator ranch rd. New Smyrna Beach, FL, USA. 32168 |

 

    On Wednesday, December 2, 2020, 03:46:42 p.m. GMT+7, annekathleenmalchow <notifications@github.com> wrote:  
 
 


So have you tried the updated version already and does it still give the same error?

**Comment by annekathleenmalchow** [comment]
Ok, thanks! Yes, that sounds like it should work on your machine.

But, please excuse me, as I don't quite understand: Have you tried the install again, after I have made the changes to the package yesterday? If so, does it give the same error as before? Could you please paste the error message here again?

**Comment by RussellGrayxd** [comment]
I tried  just now, again the same issue.

Enter one or more numbers, or an empty line to skip updates:√  checking for file 'C:\Users\Russe\AppData\Local\Temp\RtmpGM5Ur3\remotes39f87a779be\RangeShifter-RangeShiftR-package-fb379e3/DESCRIPTION' ...-  preparing 'RangeShiftR': (459ms)√  checking DESCRIPTION meta-information ... -  cleaning src-  installing the package to process help pages         ------------------------------------  installing *source* package 'RangeShiftR' ...   ** using staged installation   ** libs   C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG  -I"C:/Users/Russe/Documents/R/win-library/3.6/Rcpp/include"     -DRSWIN64 -w   -O2 -Wall  -mtune=core2 -c Cell.cpp -o Cell.o   C:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG  -I"C:/Users/Russe/Documents/R/win-library/3.6/Rcpp/include"     -DRSWIN64 -w   -O2 -Wall  -mtune=core2 -c Community.cpp -o Community.o   In file included from SubCommunity.h:55:0,                    from Community.h:57,                    from Community.cpp:25:   Landscape.h:92:19: fatal error: codecvt: No such file or directory    #include <codecvt>                      ^   compilation terminated.   make: *** [C:/PROGRA~1/R/R-36~1.3/etc/x64/Makeconf:215: Community.o] Error 1   ERROR: compilation failed for package 'RangeShiftR'-  removing 'C:/Users/Russe/AppData/Local/Temp/RtmpeIAqcC/Rinst2fc827d259a8/RangeShiftR'         -----------------------------------   ERROR: package installation failedError: Failed to install 'RangeShiftR' from GitHub:  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):E>                  from Community.cpp:25:E> Landscape.h:92:19: fatal error: codecvt: No such file or directoryE>  #include <codecvt>E>                    ^E> compilation terminated.E> make: *** [C:/PROGRA~1/R/R-36~1.3/etc/x64/Makeconf:215: Community.o] Error 1E> ERROR: compilation failed for package 'RangeShiftR'E> * removing 'C:/Users/Russe/AppData/Local/Temp/RtmpeIAqcC/Rinst2fc827d259a8/RangeShiftR'E>       -----------------------------------E> ERROR: package installation failed

--Russell J. Gray
Wildlife Ecology & Conservation Consultant
| 
0934581341 | rgrayherpetology@gmail.com
 |
| 
https://www.rjgrayecology.com/
 |
| 705 alligator ranch rd. New Smyrna Beach, FL, USA. 32168 |

 

    On Wednesday, December 2, 2020, 04:22:59 p.m. GMT+7, annekathleenmalchow <notifications@github.com> wrote:  
 
 


Ok, thanks! Yes, that sounds like it should work on your machine.

But, please excuse me, as I don't quite understand: Have you tried the install again, after I have made the changes to the package yesterday? If so, does it give the same error as before? Could you please paste the error message here again?

**Comment by annekathleenmalchow** [comment]
Alright, thanks for this!
I think I have found the culprit. Please, if you could try it again?
Thanks for your patience.

**Comment by RussellGrayxd** [comment]
Tried again and now its running a new error:

√  checking for file 'C:\Users\Russe\AppData\Local\Temp\Rtmp2hAXi6\remotes2848d315f67\RangeShifter-RangeShiftR-package-e117856/DESCRIPTION' ...-  preparing 'RangeShiftR': (546ms)√  checking DESCRIPTION meta-information ... -  cleaning src-  installing the package to process help pages         ------------------------------------  installing *source* package 'RangeShiftR' ...   ** using staged installation   ** libs   c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG  -I"C:/Users/Russe/Documents/R/win-library/3.6/Rcpp/include"     -DRSWIN64 -w   -O2 -Wall  -mtune=core2 -c Cell.cpp -o Cell.o   c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG  -I"C:/Users/Russe/Documents/R/win-library/3.6/Rcpp/include"     -DRSWIN64 -w   -O2 -Wall  -mtune=core2 -c Community.cpp -o Community.o   c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG  -I"C:/Users/Russe/Documents/R/win-library/3.6/Rcpp/include"     -DRSWIN64 -w   -O2 -Wall  -mtune=core2 -c FractalGenerator.cpp -o FractalGenerator.o   c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG  -I"C:/Users/Russe/Documents/R/win-library/3.6/Rcpp/include"     -DRSWIN64 -w   -O2 -Wall  -mtune=core2 -c Genome.cpp -o Genome.o   c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG  -I"C:/Users/Russe/Documents/R/win-library/3.6/Rcpp/include"     -DRSWIN64 -w   -O2 -Wall  -mtune=core2 -c Individual.cpp -o Individual.o   c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG  -I"C:/Users/Russe/Documents/R/win-library/3.6/Rcpp/include"     -DRSWIN64 -w   -O2 -Wall  -mtune=core2 -c Landscape.cpp -o Landscape.o   c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG  -I"C:/Users/Russe/Documents/R/win-library/3.6/Rcpp/include"     -DRSWIN64 -w   -O2 -Wall  -mtune=core2 -c Model.cpp -o Model.o   c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG  -I"C:/Users/Russe/Documents/R/win-library/3.6/Rcpp/include"     -DRSWIN64 -w   -O2 -Wall  -mtune=core2 -c Parameters.cpp -o Parameters.o   c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG  -I"C:/Users/Russe/Documents/R/win-library/3.6/Rcpp/include"     -DRSWIN64 -w   -O2 -Wall  -mtune=core2 -c Patch.cpp -o Patch.o   c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG  -I"C:/Users/Russe/Documents/R/win-library/3.6/Rcpp/include"     -DRSWIN64 -w   -O2 -Wall  -mtune=core2 -c Population.cpp -o Population.o   c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG  -I"C:/Users/Russe/Documents/R/win-library/3.6/Rcpp/include"     -DRSWIN64 -w   -O2 -Wall  -mtune=core2 -c RSrandom.cpp -o RSrandom.o   c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG  -I"C:/Users/Russe/Documents/R/win-library/3.6/Rcpp/include"     -DRSWIN64 -w   -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o   c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.3/include" -DNDEBUG  -I"C:/Users/Russe/Documents/R/win-library/3.6/Rcpp/include"     -DRSWIN64 -w   -O2 -Wall  -mtune=core2 -c Rinterface.cpp -o Rinterface.o   In file included from Rinterface.cpp:43:0:   Rinterface.h:63:25: fatal error: RandomCheck.h: No such file or directory    #include "RandomCheck.h"                            ^   compilation terminated.   make: *** [C:/PROGRA~1/R/R-36~1.3/etc/x64/Makeconf:215: Rinterface.o] Error 1   ERROR: compilation failed for package 'RangeShiftR'-  removing 'C:/Users/Russe/AppData/Local/Temp/RtmpAhXnr8/Rinst34b81584755a/RangeShiftR'         -----------------------------------   ERROR: package installation failedError: Failed to install 'RangeShiftR' from GitHub:  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):E> In file included from Rinterface.cpp:43:0:E> Rinterface.h:63:25: fatal error: RandomCheck.h: No such file or directoryE>  #include "RandomCheck.h"E>                          ^E> compilation terminated.E> make: *** [C:/PROGRA~1/R/R-36~1.3/etc/x64/Makeconf:215: Rinterface.o] Error 1E> ERROR: compilation failed for package 'RangeShiftR'E> * removing 'C:/Users/Russe/AppData/Local/Temp/RtmpAhXnr8/Rinst34b81584755a/RangeShiftR'E>       -----------------------------------E> ERROR: package installation failed

--Russell J. Gray
Wildlife Ecology & Conservation Consultant
| 
0934581341 | rgrayherpetology@gmail.com
 |
| 
https://www.rjgrayecology.com/
 |
| 705 alligator ranch rd. New Smyrna Beach, FL, USA. 32168 |

 

    On Wednesday, December 2, 2020, 05:40:54 p.m. GMT+7, annekathleenmalchow <notifications@github.com> wrote:  
 
 


Alright, thanks for this!
I think I have found the culprit. Please, if you could try it again?
Thanks for your patience.

**Comment by annekathleenmalchow** [comment]
Sorry about this! 
We had made a bunch of small changes to the code and it worked alright on my machine. Anyway, I hope it should be sorted now. Sorry for having you test the package installation, but it should work now.

**Comment by RussellGrayxd** [comment]
It works! Thanks for everything!
--Russell J. Gray
Wildlife Ecology & Conservation Consultant
| 
0934581341 | rgrayherpetology@gmail.com
 |
| 
https://www.rjgrayecology.com/
 |
| 705 alligator ranch rd. New Smyrna Beach, FL, USA. 32168 |

 

    On Wednesday, December 2, 2020, 06:08:21 p.m. GMT+7, annekathleenmalchow <notifications@github.com> wrote:  
 
 


Sorry about this!
We had made a bunch of small changes to the code and it worked alright on my machine. Anyway, I hope it should be sorted now. Sorry for having you test the package installation, but it should work now.

**Comment by annekathleenmalchow** [comment]
Awesome, I am glad to hear this. Sorry again for the hassle and thanks for your patience!
Let us know if you have more questions about the package
