### ISSUE TITLE
Error reading initial distribution for landscape 0 - aborting

### ISSUE THREAD

**Issue by robboyd** [RangeShifter/RangeShiftR-package#4]
I am trying to load species' initial distributions using .asc files with 1s and 0s. The format is identical to the habitat suitability inputs, which are read in with no problem. I get the error `At (x,y) = 1,1249 :
*** Corrupted file stream in C:/Users/robboy/Documents/RangeShiftR/Inputs/init_dist_1.asc
Too few entries? Unsuppoerted file encoding? (You might try to use a different one, like UTF-8.)

Error reading initial distribution for landscape 0 - aborting`

I don' think any of the suggested issues are to blame as the the initial distribution files were created in an identical manner to the habitat files, which are read in fine. 

Any help would be much appreciated

**Comment by scfpalmer** [comment]
Hi Rob

If this is till an outstanding issue, would you please send me your habitat and initial distributions layers, and I'll take a look at them. Please mail them to me directly at s.palmer@abdn.ac.uk

Steve

**Comment by robboyd** [comment]
Thanks Steve. The problem was with the format of the raster files I used. The raster package spits out rasters whose xmax, ymax value has many decimal places. RangeShiftR didn't like this. Imagine others who process their rasters using the raster package might have a similar problem. Hope that helps
